# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      #- name: Setup Node.js environment
      #  uses: actions/setup-node@v2.1.4
      #  with:
      #    node-version: 12.x
      
      # Instalar as dependencias do NPM/Yarn
      #- name: Install dependencies
      #  run: yarn
      
      # Executar a build
      #- name: Run build
      #  run: yarn build
      
      # Copiar pasta dist pra dentro da digital ocean
#       - name: Copy code to Digital OCean
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USER }}
#           port: ${{ secrets.SSH_PORT }}
#           key: ${{ secrets.SSH_KEY }}
#           source: ".,!node_modules"
#           target: "~/app/fba-control-api"

      # Executar yarn na Digital Ocean
      # Executar as migrations do TypeOrm
      # Restart no servidor node
      - name: Install dependencies on Digital Ocean ! Run Migrations ! Restart Node
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: | 
            cd ~/app/fba-control-api
            git pull -f origin master
            yarn
            yarn build            
            ./node_modules/.bin/typeorm migration:run
            pm2 restart fhseller-api
